# Generated by Django 5.2.11 on 2026-02-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='disease_detection/%Y/%m/%d/')),
                ('detected_disease', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(blank=True, choices=[('Mild', 'Mild - <20% leaf damage'), ('Moderate', 'Moderate - 50% damage'), ('Severe', 'Severe - >50% damage')], max_length=20)),
                ('treatments', models.JSONField(default=dict)),
                ('prevention_tips', models.TextField(blank=True)),
                ('similar_cases_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseTreatmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_applied', models.CharField(max_length=255)),
                ('treatment_type', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical')], max_length=20)),
                ('cost_actual', models.FloatField()),
                ('effectiveness', models.IntegerField(default=0)),
                ('days_to_recovery', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.diseasedetection')),
            ],
        ),
    ]
