# Generated by Django 5.2.11 on 2026-02-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_diseasedetection_diseasetreatmentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('water', 'Water'), ('fertilizer', 'Fertilizer'), ('labor', 'Labor'), ('other', 'Other')], max_length=50)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
