# Generated by Django 5.2.11 on 2026-03-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('water', 'Watering'), ('fertilizer', 'Fertilizer application')], max_length=50)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
