# Generated by Django 5.2.11 on 2026-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_cropactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropactivity',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
