# Generated by Django 5.2.11 on 2026-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0007_agriculturealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], unique=True)),
                ('sunrise', models.CharField(help_text='Format: HH:MM AM/PM, e.g., 06:30 AM', max_length=20)),
                ('sunset', models.CharField(help_text='Format: HH:MM PM, e.g., 06:30 PM', max_length=20)),
                ('daylight_hours', models.FloatField(help_text='Total daylight hours, e.g., 12.5')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.DeleteModel(
            name='AgricultureAlert',
        ),
    ]
